"""
Book name and ID mappings for Hebrew Bible search.
"""

# Hebrew book name to book_id mapping (all 37 books from metadata.json)
HEBREW_BOOK_MAP = {
    # Torah
    'בראשית': 'bereshit',
    'שמות': 'shemot',
    'ויקרא': 'vayikra',
    'במדבר': 'bamidbar',
    'דברים': 'devarim',
    # Former Prophets
    'יהושע': 'yehoshua',
    'שופטים': 'shoftim',
    'שמואל א': 'shmuel_alef',
    'שמואל ב': 'shmuel_bet',
    'מלכים א': 'melachim_alef',
    'מלכים ב': 'melachim_bet',
    # Latter Prophets
    'ירמיהו': 'yirmiyahu',
    'יחזקאל': 'yechezkel',
    'הושע': 'hoshea',
    'יואל': 'yoel',
    'עמוס': 'amos',
    'עובדיה': 'ovadya',
    'יונה': 'yona',
    'מיכה': 'micha',
    'נחום': 'nachum',
    'חבקוק': 'chavakuk',
    'צפניה': 'tzefanya',
    'חגי': 'chagai',
    'זכריה': 'zecharya',
    'מלאכי': 'malachi',
    # Writings
    'תהלים': 'tehilim',
    'משלי': 'mishlei',
    'איוב': 'iyov',
    'שיר השירים': 'shir_hashirim',
    'רות': 'rut',
    'איכה': 'eicha',
    'קהלת': 'kohelet',
    'אסתר': 'esther',
    'דניאל': 'daniel',
    'עזרא': 'ezra',
    'נחמיה': 'nechemya',
    'דברי הימים א': 'divrei_hayamim_alef',
    'דברי הימים ב': 'divrei_hayamim_bet',
}

# Book ID aliases for normalization - maps common variations to canonical IDs
BOOK_ID_ALIASES = {
    # Shmuel variations
    'shmuel1': 'shmuel_alef',
    'shmuel_1': 'shmuel_alef',
    'shmuel_a': 'shmuel_alef',
    'shemuel1': 'shmuel_alef',
    'shemuel_alef': 'shmuel_alef',
    '1_shmuel': 'shmuel_alef',
    '1_samuel': 'shmuel_alef',
    'samuel_1': 'shmuel_alef',
    'shmuel2': 'shmuel_bet',
    'shmuel_2': 'shmuel_bet',
    'shmuel_b': 'shmuel_bet',
    'shemuel2': 'shmuel_bet',
    'shemuel_bet': 'shmuel_bet',
    '2_shmuel': 'shmuel_bet',
    '2_samuel': 'shmuel_bet',
    'samuel_2': 'shmuel_bet',
    # Melachim variations
    'melachim1': 'melachim_alef',
    'melachim_1': 'melachim_alef',
    'melachim_a': 'melachim_alef',
    '1_melachim': 'melachim_alef',
    '1_kings': 'melachim_alef',
    'kings_1': 'melachim_alef',
    'melachim2': 'melachim_bet',
    'melachim_2': 'melachim_bet',
    'melachim_b': 'melachim_bet',
    '2_melachim': 'melachim_bet',
    '2_kings': 'melachim_bet',
    'kings_2': 'melachim_bet',
    # Divrei Hayamim variations
    'divrei_hayamim1': 'divrei_hayamim_alef',
    'divrei_hayamim_1': 'divrei_hayamim_alef',
    'divrei_hayamim_a': 'divrei_hayamim_alef',
    '1_divrei_hayamim': 'divrei_hayamim_alef',
    '1_chronicles': 'divrei_hayamim_alef',
    'chronicles_1': 'divrei_hayamim_alef',
    'divrei_hayamim2': 'divrei_hayamim_bet',
    'divrei_hayamim_2': 'divrei_hayamim_bet',
    'divrei_hayamim_b': 'divrei_hayamim_bet',
    '2_divrei_hayamim': 'divrei_hayamim_bet',
    '2_chronicles': 'divrei_hayamim_bet',
    'chronicles_2': 'divrei_hayamim_bet',
    # Common English name variations
    'genesis': 'bereshit',
    'exodus': 'shemot',
    'leviticus': 'vayikra',
    'numbers': 'bamidbar',
    'deuteronomy': 'devarim',
    'joshua': 'yehoshua',
    'judges': 'shoftim',
    'ruth': 'rut',
    'psalms': 'tehilim',
    'proverbs': 'mishlei',
    'job': 'iyov',
    'song_of_songs': 'shir_hashirim',
    'ecclesiastes': 'kohelet',
    'lamentations': 'eicha',
    'esther': 'esther',
    'daniel': 'daniel',
    'ezra': 'ezra',
    'nehemiah': 'nechemya',
    'isaiah': 'yeshayahu',
    'jeremiah': 'yirmiyahu',
    'ezekiel': 'yechezkel',
    'hosea': 'hoshea',
    'joel': 'yoel',
    'amos': 'amos',
    'obadiah': 'ovadya',
    'jonah': 'yona',
    'micah': 'micha',
    'nahum': 'nachum',
    'habakkuk': 'chavakuk',
    'zephaniah': 'tzefanya',
    'haggai': 'chagai',
    'zechariah': 'zecharya',
    'malachi': 'malachi',
}